### ISSUE TITLE
Win11 +miniconda3+pycharm +mySQL8.0.36 运行qteasy-1.0.26求助 

### ISSUE THREAD

**Issue by ziarcher** [shepherdpp/qteasy#122]
大佬空闲时帮看看，谢谢！
<img width="936" alt="屏幕截图 2024-03-02 111417" src="https://github.com/shepherdpp/qteasy/assets/55844392/333336a4-96a0-4808-905b-e4fef7447d48">
<img width="936" alt="屏幕截图 2024-03-02 111529" src="https://github.com/shepherdpp/qteasy/assets/55844392/e43826e4-64b4-49b8-8706-71612da774c4">
<img width="960" alt="屏幕截图 2024-03-02 111622" src="https://github.com/shepherdpp/qteasy/assets/55844392/2d49d2bc-e8a8-431e-ba2f-0291f5cad2ca">
<img width="738" alt="屏幕截图 2024-03-02 112028" src="https://github.com/shepherdpp/qteasy/assets/55844392/9ab6ff0b-3dd8-486b-b810-025597f7dce5">

C:\Users\yuewe\.conda\envs\qteasy-env\python.exe C:\Users\yuewe\Documents\GitHub\qteasy-1.0.26\start\import_qteasy.py 
C:\Users\yuewe\Documents\GitHub\qteasy-1.0.26\qteasy\database.py:2504: RuntimeWarning: (1045, "Access denied for user 'yuewe'@'localhost' (using password: NO)"), Can not set data source type to "db", will fall back to default type
  warnings.warn(f'{str(e)}, Can not set data source type to "db",'
1.0.26
C:\Users\yuewe\Documents\GitHub\qteasy-1.0.26\qteasy\__init__.py:127: UserWarning: trade calendar is not loaded, some utility functions may not work properly, to download trade calendar, run 
"qt.refill_data_source(tables='trade_calendar')"
  warnings.warn(f'trade calendar is not loaded, some utility functions may not work '
<img width="929" alt="1709349152934" src="https://github.com/shepherdpp/qteasy/assets/55844392/be42b0f1-c7dd-4dbb-883c-620e4fe360f2">

**Comment by ziarcher** [comment]
<img width="960" alt="屏幕截图 2024-03-02 114651" src="https://github.com/shepherdpp/qteasy/assets/55844392/d257b857-0380-4e8a-9ce7-f836a1f06605">
<img width="960" alt="屏幕截图 2024-03-02 114815" src="https://github.com/shepherdpp/qteasy/assets/55844392/37559b4c-7f0f-4e7c-a200-b2317bace4af">

**Comment by shepherdpp** [comment]
初步看下来，问题应该出在您的qteasy.cfg文件上。在文件中给出配置信息的时候，请不要加`<`和`>`，否则，这些字符也会被认为是`token`或者数据库名的一部份。

`qteasy`在解析配置文件的时候，会根据配置的类型，自动转换为正确的格式，例如，数据库端口`3306`应该是`int`变量，直接使用

```
local_db_port = 3306
```

即可。`qteasy`会将字符串`3306`转换为`int`型`3306`。·

下面这个配置文件的例子是正确的：

```
tushare_token = 2dff3f034aa966479c81e4b4b0736fb081b740abb2xxxxxxxxxxxxxxxxxxxxx

local_data_source = database

local_db_host = localhost
local_db_port = 3306
local_db_user = user_name
local_db_password = pass_word
local_db_name = ts_db
```

**Comment by shepherdpp** [comment]
如果通过上面修改您没有遇到更多的问题，我将会把这个Issue关闭。
