### ISSUE TITLE
mysql连接错误

### ISSUE THREAD

**Issue by LuisLIn666** [shepherdpp/qteasy#188]
**Describe the bug / 描述bug内容**
C:\Users\01\pythonprogram\STOCK\STOCK\.venv\lib\site-packages\qteasy\database.py:2521: RuntimeWarning: Mysql connection failed: (1045, "Access denied for user 'linyi'@'192.168.32.1' (using password: YES)")
Can not set data source type to "db", will fall back to csv file

**To Reproduce / 复现问题**
我的mysql数据库安装在wmware上面，地址是192.168.32.131

**Expected behavior / 期望的输出**
能够连接上数据库下载文件

**Environment (please complete the following information) / 请提供更多环境信息:**
 - Versions [versions of your `python` environment and `qteasy` / `Python`的版本和`qteasy`的版本]   python 3.9

**Additional context / 其他信息**

qteasy.cfg
![微信截图_20241025211343](https://github.com/user-attachments/assets/74131ae2-d176-4422-829f-2ed020705abe)
报错信息
![微信截图_20241025211440](https://github.com/user-attachments/assets/98ba00fb-8926-40f3-a8e9-01da2627e7e2)
自己写的测试用例
![微信截图_20241025211457](https://github.com/user-attachments/assets/4fc8747c-1226-4976-8658-16a35dcd3a3b)

**Comment by LuisLIn666** [comment]
database.py文件
![image](https://github.com/user-attachments/assets/1b606ad0-6a5d-48b2-a0c6-73a47a5ae6fc)

**Comment by shepherdpp** [comment]
您遇到了qteasy中的一个bug：当您的密码是纯数字字符串时，它无法被正确地解析。
我会在下一个更新中解决这个问题。

在版本更新以前，您可以将密码修改为字母数字混合类型，如‘abc123’等等，修改qteasy.cfg文件如下：
local_db_password = abc123

只要确保qteasy.cfg的字符串不含引号，就能正确地解析

**Comment by shepherdpp** [comment]
找到了start-up配置文件解析函数中的一处错误，导致错误解析引号引起来的强制字符串类型。
之前的单元测试不够完善没有捕捉到这个错误，现在单元测试已经更新

请升级到qteasy v1.3.11，这个问题已经解决，请确认一下

**Comment by LuisLIn666** [comment]
可以了，谢谢
