### ISSUE TITLE
能否通过Wind、同花顺这类客户端获取数据，然后应用到qteasy呢？

### ISSUE THREAD

**Issue by piper0124** [shepherdpp/qteasy#192]
**Describe your need / 描述您的需求**
能否通过Wind、同花顺这类客户端获取数据（例如通过这些终端的Python接口、内置数据浏览器等），然后应用到qteasy呢？谢谢。

**Comment by shepherdpp** [comment]
我现在正在准备qteasy的下一个大升级版本，在这个版本中会实现金融数据功能的一次大升级。
在升级后的版本中，将实现一个可扩展的数据获取接口，从而更容易地兼容除tushare以外的其他数据提供商，这样即使没有tushare积分，也能愉快地从其他数据提供商获取数据。
另外，从不同渠道获得的数据都会被清洗后存入同一套统一定义的数据表中，确保来源不同的数据都有同样的可用性。
数据的提取架构也会更新，目标主打灵活性和可扩展性。

敬请期待！

**Comment by piper0124** [comment]
期待！
新年快乐 : )
