### ISSUE TITLE
setup.py没有写？

### ISSUE THREAD

**Issue by lxj0276** [shepherdpp/qteasy#25]
难道直接导入qteasy文件夹?

**Comment by shepherdpp** [comment]
qteasy还在开发中，功能还没有达到我心目中可以正式上线的标准
进度有些慢，抱歉
等达到上限标准后，会上传到pip，这时可以使用
pip install qteasy
来安装

**Comment by shepherdpp** [comment]
现在qteasy已经上线到PyPI并可以从pip安装：
pip install qteasy 

当前版本为0.0.1.dev0，有些功能还在完善中
部分依赖包需要自行安装，详情请查看README
