### ISSUE TITLE
无法复现轮动策略回测结果

### ISSUE THREAD

**Issue by caolingyu** [shepherdpp/qteasy#33]
作者你好，感谢你开发了这么一套功能齐全的量化系统！我在csdn看到你写的这篇文章
https://blog.csdn.net/Shepherdppz/article/details/124389327
我尝试用最新的代码复现『改进版』的策略，得到了如图的结果，和文章中的900%收益率相差不少，想请问作者这可能是由于什么原因导致的？

![image](https://user-images.githubusercontent.com/11562895/211734622-5416e6d1-6db4-48d9-be15-0e9041d36448.png)

我在使用中发现文章中的一些参数在最新版本的代码中已有变更，我按照这样的参数配置的回测：
```
op = qt.Operator(strategies='ndayrate', signal_type='pt')
op.set_parameter(0, 
                 sample_freq='d',
                 sort_ascending=False,
                 pars=(20, ),
                 data_types='close',
                 max_sel_count=0.5,
                 condition='greater',  # 新增过滤条件：20日涨幅大于等于
                 ubound=0)  # 过滤条件值：0

qt.configure(asset_pool=['000300.SH',
                                            '399006.SZ'],  # 投资指数包括沪深300和创业板指数
             asset_type='IDX',  # 为简单起见，直接投资于指数
             cost_rate_buy=0.0001,  # 买入资产时交易费用万分之一
             cost_rate_sell=0.0001,  # 卖出资产时的交易费用为万分之一
             invest_start='20110101',  # 模拟交易开始日期
             invest_end='20201231',  # 模拟交易结束日期
             trade_batch_size=1,  # 买入资产时最小交易批量
             sell_batch_size=0)  # 卖出资产时最小交易批量

```

**Comment by shepherdpp** [comment]
您运行“改进前”版本的策略时，结果是什么样的？我用您的代码运行后回测总收益率是387%（改进前）以及 600%左右（改进后）
建议您运行
qt.configuration(up_to=5)
查看所有的环境配置变量是否有异常
另外，请将trade_log.csv和trade_record.csv两个文件发给我jackie_pengzhao@163.com，我来检查是否有其他异常或bug，非常感谢！

**Comment by shepherdpp** [comment]
请在qt.config()中修改一个环境变量maximize_cash_usage的值，设置：
maximize_cash_usage=True
在原来版本的qteasy中，这个环境变量的默认值为True，但是在最近的升级中默认值被修改为了False
这个参数控制同一个交易日内卖出股票得到的现金是否可以在当天被用来买入股票（前提是现金交割期被设置为0，cash_deliver_period = 0），设置maximize_cash_usage=True表示允许使用当天的现金继续买入。

如果要更加详细地了解这个参数对模拟交易的具体影响，可以分别打印出两次回测的trade_log.csv 和trade_record.csv文件，逐日对比交易结果

**Comment by shepherdpp** [comment]
您好


造成回测收益率区别的最主要参数是 maximize_cash_usage


如果设置maximize_cash_usage=True，则回测收益率会达到600%左右，而如果maximize_cash_usage=False时，回测收益率只有300%不到




这个参数在原来的qteasy版本中默认值为True，最近的更新中被修改为了False




这个参数主要控制回测过程中是否允许使用当天出售一个股票（资产）获得的现金立即买入新的股票。（前提是现金交割期为0，否则这个参数无效）


为了实现更加真实的回测模拟交易结果，qteasy的回测内核有不少控制参数，有时候调整一个参数会对交易结果产生很大的影响
建议通过trade_log和trade_record文件来检查模拟交易的过程，以确保回测结果与真实情况接近


Jackie

在 2023-01-11 14:38:12，"Lingyu Cao" ***@***.***> 写道：

作者你好，感谢你开发了这么一套功能齐全的量化系统！我在csdn看到你写的这篇文章
https://blog.csdn.net/Shepherdppz/article/details/124389327
我尝试用最新的代码复现『改进版』的策略，得到了如图的结果，和文章中的900%收益率相差不少，想请问作者这可能是由于什么原因导致的？

我在使用中发现文章中的一些参数在最新版本的代码中已有变更，我按照这样的参数配置的回测：

op = qt.Operator(strategies='ndayrate', signal_type='pt')
op.set_parameter(0, 
                 sample_freq='d',
                 sort_ascending=False,
                 pars=(20, ),
                 data_types='close',
                 max_sel_count=0.5,
                 condition='greater',  # 新增过滤条件：20日涨幅大于等于
                 ubound=0)  # 过滤条件值：0

qt.configure(asset_pool=['000300.SH',
                                            '399006.SZ'],  # 投资指数包括沪深300和创业板指数
             asset_type='IDX',  # 为简单起见，直接投资于指数
             cost_rate_buy=0.0001,  # 买入资产时交易费用万分之一
             cost_rate_sell=0.0001,  # 卖出资产时的交易费用为万分之一
             invest_start='20110101',  # 模拟交易开始日期
             invest_end='20201231',  # 模拟交易结束日期
             trade_batch_size=1,  # 买入资产时最小交易批量
             sell_batch_size=0)  # 卖出资产时最小交易批量

**Comment by caolingyu** [comment]
谢谢！请问目前支持实时交易模式吗？

**Comment by shepherdpp** [comment]
实盘交易模式是在现在的开发计划中


2023.01开发计划：
1，项目上线PyPI -- 进度：项目build已经完成，正在进行环境测试，将很快上线第一个dev版本
2，实盘交易模块完善 -- 目前queasy仅有实盘交易的最基本模块，尚未实用化，计划将实现实时交易数据获取和策略定期自动运行
3，历史数据分析模块 -- 实现更多的历史数据分析和可视化功能，帮助分析数据创建交易策略











在 2023-01-17 16:46:37，"Lingyu Cao" ***@***.***> 写道：

谢谢！请问目前支持实时交易模式吗？

**Comment by shepherdpp** [comment]
追加解释为何之前几个版本的qteasy的回测结果有差异：
问题出在进行日线模拟交易的时候，是否允许使用当天的最新价格来生成交易信号。在最早的版本中，利用日频数据生成交易信号的时候，是可以使用当天的最新数据的，例如，策略在3月5日收盘时运行的时候，可以使用3月5日当天的数据以及3月5日以前的数据生成交易信号，并在当天交易。但是在后续的几个版本中，针对这条设定进行了调整。使得3月5日只能使用3月5日以前的数据，当天数据不能使用。这主要是为了避免在策略中出现未来函数，因此将当天可能无法获取的所有数据都排除在外了。

这样调整的内在逻辑是，如果在3月5日进行策略计算，有可能部分当天的数据是不可用的。当然，这样调整造成的结果就是，所有的交易策略都会晚一个周期产生，造成策略运行滞后。这种滞后几乎在所有的情况下都会导致回测的结果更差。
然而，在实际的交易环节，为了避免策略运行滞后，策略还是应该始终设法使用最新的数据来生成交易信号的，尤其是低频运行的策略。如果一个周频交易策略永远只能用上周的数据生成交易信号，或者月频的策略只能使用上个月的数据，那交易滞后性将会导致非常严重的后果。在实践中，大家肯定会想方设法使用最新的数据来弥补。例如，一个策略被设定在3月5日收盘时运行，通过收盘价的变化率产生交易信号，当然3月5日的收盘价是一个未知数，因为策略必须在收盘前运行，而收盘前是不可能知道当天的收盘价的。但是，我们可以设定策略在3月5日收盘前1分钟运行，并使用收盘前1分钟的价格作为收盘价来跑策略，这样就相当于使用了当天的数据。更不用说，除了收盘价未知以外，在收盘前1分钟其他很多数据都是可以比较精确地估算出来的。

因此，在最新的queasy版本中（v1.0.7），交易策略多了一个属性“strategy.use_latest_data_cycle"，为True时，这个交易策略在回测时会直接使用当天（或当时）的最新数据来生成交易信号，在实盘运行时，会读取策略运行时的最新的价格数据作为当天或当时的数据来生成交易信号。如果设置为False，则只会使用前一个周期的数据。

这样，在跑长期的日频模拟交易回测时，例如我在文章https://blog.csdn.net/Shepherdppz/article/details/124389327中介绍的策略，将策略属性use_latest_data_cycle设置为True，就能得到文章中的结果。反之设置为False，结果就会差很多，这是由于策略运行滞后导致的。

同时，用户应该根据策略的运行时机和性质来设置use_latest_data_cycle属性。例如，如果策略在每日开盘时运行，但需要用到与收盘价相关的数据，或当天收盘后才知道的数据，例如收盘价、成交量、pe等等，则应该将此属性设置为False，确保策略在每天开盘时运行，只能用前一天的收盘价计算交易信号。
